import { PostCategory, PostSubcategory } from "@prisma/client";

export const POST_CATEGORY_LABELS: Record<PostCategory, string> = {
  MEDICINA_DO_TRABALHO: "Medicina do Trabalho",
  SEGURANCA_DO_TRABALHO: "Segurança do Trabalho",
  GESTAO_EMPRESARIAL: "Gestão Empresarial",
  FINANCEIRO_E_CONTABIL: "Financeiro e Contábil",
  JURIDICO_E_LEGISLACAO: "Jurídico e Legislação",
  INSTITUCIONAL_E_COMERCIAL: "Institucional e Comercial",
  TECNOLOGIA_DA_INFORMACAO: "Tecnologia da Informação",
  NOVIDADES: "Novidades",
  FRANQUIAS: "Franquias",
};

export const POST_SUBCATEGORY_LABELS: Record<PostSubcategory, string> = {
  GERAL: "Geral",

  PCMSO: "PCMSO",
  EXAMES_OCUPACIONAIS: "Exames Ocupacionais",
  EXAME_ADMISSIONAL: "Exame Admissional",
  EXAME_PERIODICO: "Exame Periódico",
  EXAME_DE_RETORNO_AO_TRABALHO: "Exame de Retorno ao Trabalho",
  EXAME_DE_MUDANCA_DE_FUNCAO: "Exame de Mudança de Função",
  EXAME_DEMISSIONAL: "Exame Demissional",
  ASO: "ASO",
  ATESTADOS_E_LAUDOS: "Atestados e Laudos",
  ATESTADO_DE_SAUDE_OCUPACIONAL: "Atestado de Saúde Ocupacional",
  LAUDOS_OCUPACIONAIS: "Laudos Ocupacionais",
  LAUDOS_ERGONOMICOS: "Laudos Ergonômicos",
  SAUDE_OCUPACIONAL: "Saúde Ocupacional",
  SAUDE_MENTAL: "Saúde Mental",
  SAUDE_PREVENTIVA: "Saúde Preventiva",
  PROMOCAO_DA_SAUDE: "Promoção da Saúde",
  QUALIDADE_DE_VIDA: "Qualidade de Vida",
  QUALIDADE_DE_VIDA_NO_TRABALHO: "Qualidade de Vida no Trabalho",
  GINASTICA_LABORAL: "Ginástica Laboral",
  VACINACAO: "Vacinação",
  PRIMEIROS_SOCORROS: "Primeiros Socorros",
  FONOAUDIOLOGIA_OCUPACIONAL: "Fonoaudiologia Ocupacional",
  ERGONOMIA: "Ergonomia",
  DOENCAS_OCUPACIONAIS: "Doenças Ocupacionais",
  DOENCAS_RESPIRATORIAS: "Doenças Respiratórias",
  AUDICAO_E_CONSERVACAO_AUDITIVA: "Audição e Conservação Auditiva",
  SAUDE_VISUAL: "Saúde Visual",
  ALIMENTACAO_SAUDAVEL: "Alimentação Saudável",
  HABITOS_SAUDAVEIS: "Hábitos Saudáveis",
  HIDRATACAO: "Hidratação",
  SONO_E_DESCANSO: "Sono e Descanso",
  BEM_ESTAR_NO_TRABALHO: "Bem-estar no Trabalho",
  SAUDE_DA_MULHER: "Saúde da Mulher",
  SAUDE_DO_HOMEM: "Saúde do Homem",
  SAUDE_DA_FAMILIA: "Saúde da Família",
  AUTOCUIDADO: "Autocuidado",
  HIGIENE_PESSOAL: "Higiene Pessoal",
  HIGIENE_NO_TRABALHO: "Higiene no Trabalho",
  CAMPANHAS_DE_SAUDE: "Campanhas de Saúde",
  BOAS_PRATICAS_DE_SAUDE: "Boas Práticas de Saúde",

  PGR: "PGR",
  GRO: "GRO",
  LTCAT: "LTCAT",
  PPP: "PPP",
  ESOCIAL: "eSocial",
  SST: "SST",
  NORMAS_REGULAMENTADORAS: "Normas Regulamentadoras",
  NR_01: "NR 01",
  NR_05: "NR 05",
  NR_06: "NR 06",
  NR_07: "NR 07",
  NR_09: "NR 09",
  NR_10: "NR 10",
  NR_11: "NR 11",
  NR_12: "NR 12",
  NR_13: "NR 13",
  NR_17: "NR 17",
  NR_18: "NR 18",
  NR_20: "NR 20",
  NR_23: "NR 23",
  NR_24: "NR 24",
  NR_26: "NR 26",
  NR_33: "NR 33",
  NR_35: "NR 35",
  TREINAMENTOS: "Treinamentos",
  DSS: "DSS",
  SIPAT: "SIPAT",
  EPI: "EPI",
  EPC: "EPC",
  EPI_E_EPC: "EPI e EPC",
  ANALISE_DE_RISCO: "Análise de Risco",
  INVESTIGACAO_DE_ACIDENTES: "Investigação de Acidentes",
  PREVENCAO_DE_ACIDENTES: "Prevenção de Acidentes",
  MAPA_DE_RISCO: "Mapa de Risco",
  HIGIENE_OCUPACIONAL: "Higiene Ocupacional",
  AGENTES_FISICOS: "Agentes Físicos",
  AGENTES_QUIMICOS: "Agentes Químicos",
  AGENTES_BIOLOGICOS: "Agentes Biológicos",
  SEGURANCA_EM_ALTURA: "Segurança em Altura",
  ESPACO_CONFINADO: "Espaço Confinado",
  SEGURANCA_ELETRICA: "Segurança Elétrica",
  SEGURANCA_EM_MAQUINAS_E_EQUIPAMENTOS: "Segurança em Máquinas e Equipamentos",
  COMBATE_A_INCENDIO: "Combate a Incêndio",
  BRIGADA_DE_INCENDIO: "Brigada de Incêndio",
  SINALIZACAO_DE_SEGURANCA: "Sinalização de Segurança",
  INSPECAO_DE_SEGURANCA: "Inspeção de Segurança",
  DOCUMENTACAO_DE_SST: "Documentação de SST",
  BOAS_PRATICAS_DE_SEGURANCA: "Boas Práticas de Segurança",

  ADMINISTRACAO: "Administração",
  GESTAO_EMPRESARIAL: "Gestão Empresarial",
  GESTAO_ESTRATEGICA: "Gestão Estratégica",
  PLANEJAMENTO_ESTRATEGICO: "Planejamento Estratégico",
  ORGANIZACAO_EMPRESARIAL: "Organização Empresarial",
  PROCESSOS_E_PRODUTIVIDADE: "Processos e Produtividade",
  MAPEAMENTO_DE_PROCESSOS: "Mapeamento de Processos",
  PADRONIZACAO_DE_PROCESSOS: "Padronização de Processos",
  INDICADORES_DE_DESEMPENHO: "Indicadores de Desempenho",
  KPI: "KPI",
  BSC: "BSC",
  QUALIDADE_E_CERTIFICACOES: "Qualidade e Certificações",
  ISO: "ISO",
  MELHORIA_CONTINUA: "Melhoria Contínua",
  GESTAO_DE_RISCOS: "Gestão de Riscos",
  GESTAO_DE_CRISES: "Gestão de Crises",
  TOMADA_DE_DECISAO: "Tomada de Decisão",
  LIDERANCA: "Liderança",
  CULTURA_EMPRESARIAL: "Cultura Empresarial",
  GOVERNANCA: "Governança",
  SUSTENTABILIDADE_EMPRESARIAL: "Sustentabilidade Empresarial",
  RESPONSABILIDADE_SOCIAL: "Responsabilidade Social",
  EMPREENDEDORISMO: "Empreendedorismo",
  INOVACAO_E_TECNOLOGIA: "Inovação e Tecnologia",
  PLANEJAMENTO_ORGANIZACIONAL: "Planejamento Organizacional",
  RECURSOS_HUMANOS: "Recursos Humanos",
  DEPARTAMENTO_PESSOAL: "Departamento Pessoal",
  GESTAO_DE_PESSOAS: "Gestão de Pessoas",
  LIDERANCA_E_GESTAO_DE_EQUIPES: "Liderança e Gestão de Equipes",
  RECRUTAMENTO_E_SELECAO: "Recrutamento e Seleção",
  ADMISSAO_E_DEMISSAO: "Admissão e Demissão",
  TREINAMENTO_E_DESENVOLVIMENTO: "Treinamento e Desenvolvimento",
  CLIMA_ORGANIZACIONAL: "Clima Organizacional",
  ENGAJAMENTO: "Engajamento",
  RETENCAO_DE_TALENTOS: "Retenção de Talentos",
  AVALIACAO_DE_DESEMPENHO: "Avaliação de Desempenho",
  CARGOS_E_SALARIOS: "Cargos e Salários",
  BENEFICIOS: "Benefícios",
  COMUNICACAO_INTERNA: "Comunicação Interna",
  ENDOMARKETING: "Endomarketing",
  DIVERSIDADE_E_INCLUSAO: "Diversidade e Inclusão",
  ETICA_PROFISSIONAL: "Ética Profissional",
  COMPORTAMENTO_ORGANIZACIONAL: "Comportamento Organizacional",
  PRODUTIVIDADE_DA_EQUIPE: "Produtividade da Equipe",
  BOAS_PRATICAS_DE_GESTAO: "Boas Práticas de Gestão",

  FINANCEIRO: "Financeiro",
  FINANCAS: "Finanças",
  GESTAO_FINANCEIRA: "Gestão Financeira",
  PLANEJAMENTO_FINANCEIRO: "Planejamento Financeiro",
  FLUXO_DE_CAIXA: "Fluxo de Caixa",
  CONTAS_A_PAGAR: "Contas a Pagar",
  CONTAS_A_RECEBER: "Contas a Receber",
  CONCILIACAO_BANCARIA: "Conciliação Bancária",
  CAPITAL_DE_GIRO: "Capital de Giro",
  GESTAO_DE_CUSTOS: "Gestão de Custos",
  GESTAO_DE_DESPESAS: "Gestão de Despesas",
  REDUCAO_DE_CUSTOS: "Redução de Custos",
  PRECIFICACAO: "Precificação",
  INDICADORES_FINANCEIROS: "Indicadores Financeiros",
  ORCAMENTO_EMPRESARIAL: "Orçamento Empresarial",
  ANALISE_FINANCEIRA: "Análise Financeira",
  RENTABILIDADE: "Rentabilidade",
  LUCRATIVIDADE: "Lucratividade",
  INADIMPLENCIA: "Inadimplência",
  COBRANCA: "Cobrança",
  CREDITO: "Crédito",
  INVESTIMENTOS: "Investimentos",
  RESERVA_FINANCEIRA: "Reserva Financeira",
  EDUCACAO_FINANCEIRA: "Educação Financeira",
  CONTABILIDADE: "Contabilidade",
  CONTABILIDADE_EMPRESARIAL: "Contabilidade Empresarial",
  CONTABILIDADE_GERENCIAL: "Contabilidade Gerencial",
  CONTABILIDADE_FISCAL: "Contabilidade Fiscal",
  ESCRITURACAO_CONTABIL: "Escrituração Contábil",
  BALANCO_PATRIMONIAL: "Balanço Patrimonial",
  DRE: "DRE",
  FLUXO_DE_CAIXA_CONTABIL: "Fluxo de Caixa Contábil",
  FECHAMENTO_CONTABIL: "Fechamento Contábil",
  PLANEJAMENTO_CONTABIL: "Planejamento Contábil",
  AUDITORIA_CONTABIL: "Auditoria Contábil",
  CONTROLADORIA: "Controladoria",
  CUSTOS_E_DESPESAS: "Custos e Despesas",
  CENTRO_DE_CUSTO: "Centro de Custo",
  PATRIMONIO_EMPRESARIAL: "Patrimônio Empresarial",
  DEPRECIACAO: "Depreciação",
  PROVISOES: "Provisões",
  OBRIGACOES_ACESSORIAS: "Obrigações Acessórias",
  SPED: "SPED",
  ECD: "ECD",
  ECF: "ECF",
  NOTA_FISCAL: "Nota Fiscal",
  FATURAMENTO: "Faturamento",
  FOLHA_DE_PAGAMENTO: "Folha de Pagamento",
  ENCARGOS_SOCIAIS: "Encargos Sociais",
  IMPOSTOS_E_TRIBUTACAO: "Impostos e Tributação",
  PLANEJAMENTO_TRIBUTARIO: "Planejamento Tributário",
  OBRIGACOES_FISCAIS: "Obrigações Fiscais",
  TRIBUTOS_FEDERAIS: "Tributos Federais",
  TRIBUTOS_ESTADUAIS: "Tributos Estaduais",
  TRIBUTOS_MUNICIPAIS: "Tributos Municipais",
  REGIME_TRIBUTARIO: "Regime Tributário",
  SIMPLES_NACIONAL: "Simples Nacional",
  LUCRO_PRESUMIDO: "Lucro Presumido",
  LUCRO_REAL: "Lucro Real",
  RETENCOES: "Retenções",
  EMISSAO_DE_NOTAS: "Emissão de Notas",
  REGULARIDADE_FISCAL: "Regularidade Fiscal",
  PARCELAMENTOS: "Parcelamentos",
  BENEFICIOS_FISCAIS: "Benefícios Fiscais",
  BOAS_PRATICAS_FINANCEIRAS: "Boas Práticas Financeiras",

  JURIDICO: "Jurídico",
  LEGISLACAO: "Legislação",
  DIREITO_DO_TRABALHO: "Direito do Trabalho",
  DIREITO_EMPRESARIAL: "Direito Empresarial",
  DIREITO_PREVIDENCIARIO: "Direito Previdenciário",
  DIREITO_CIVIL: "Direito Civil",
  DIREITO_TRIBUTARIO: "Direito Tributário",
  DIREITO_ADMINISTRATIVO: "Direito Administrativo",
  COMPLIANCE: "Compliance",
  CONTRATOS: "Contratos",
  RESPONSABILIDADE_CIVIL: "Responsabilidade Civil",
  PASSIVO_TRABALHISTA: "Passivo Trabalhista",
  AUDITORIA_JURIDICA: "Auditoria Jurídica",
  ADEQUACAO_LEGAL: "Adequação Legal",
  NORMAS_E_REGULAMENTACOES: "Normas e Regulamentações",
  PORTARIAS: "Portarias",
  DECRETOS: "Decretos",
  OBRIGACOES_LEGAIS: "Obrigações Legais",
  FISCALIZACAO: "Fiscalização",
  DEFESA_ADMINISTRATIVA: "Defesa Administrativa",
  JURISPRUDENCIA: "Jurisprudência",
  REFORMA_TRABALHISTA: "Reforma Trabalhista",
  LGPD: "LGPD",
  DOCUMENTACAO_LEGAL: "Documentação Legal",
  BOAS_PRATICAS_JURIDICAS: "Boas Práticas Jurídicas",

  INSTITUCIONAL: "Institucional",
  SOBRE_A_EMPRESA: "Sobre a Empresa",
  HISTORIA_DA_EMPRESA: "História da Empresa",
  MISSAO_VISAO_E_VALORES: "Missão, Visão e Valores",
  EVENTOS: "Eventos",
  FEIRAS_E_CONGRESSOS: "Feiras e Congressos",
  COMEMORACOES: "Comemorações",
  ANIVERSARIO_DA_EMPRESA: "Aniversário da Empresa",
  DATAS_COMEMORATIVAS: "Datas Comemorativas",
  FERIADOS: "Feriados",
  FERIADOS_NACIONAIS: "Feriados Nacionais",
  FERIADOS_ESTADUAIS: "Feriados Estaduais",
  FERIADOS_MUNICIPAIS: "Feriados Municipais",
  CAMPANHAS: "Campanhas",
  CAMPANHAS_DE_CONSCIENTIZACAO: "Campanhas de Conscientização",
  PREMIOS_E_RECONHECIMENTOS: "Prêmios e Reconhecimentos",
  CERTIFICACOES_E_CONQUISTAS: "Certificações e Conquistas",
  PARCERIAS: "Parcerias",
  MIDIA_E_IMPRENSA: "Mídia e Imprensa",
  COMUNICADOS_OFICIAIS: "Comunicados Oficiais",
  NOVIDADES_INSTITUCIONAIS: "Novidades Institucionais",
  COMERCIAL: "Comercial",
  VENDAS: "Vendas",
  ATENDIMENTO_AO_CLIENTE: "Atendimento ao Cliente",
  RELACIONAMENTO_COM_CLIENTES: "Relacionamento com Clientes",
  EXPERIENCIA_DO_CLIENTE: "Experiência do Cliente",
  POS_VENDA: "Pós-venda",
  MARKETING: "Marketing",
  MARKETING_DIGITAL: "Marketing Digital",
  POSICIONAMENTO_DE_MARCA: "Posicionamento de Marca",
  CAMPANHAS_COMERCIAIS: "Campanhas Comerciais",
  BOAS_PRATICAS_COMERCIAIS: "Boas Práticas Comerciais",

  SEGURANCA_DA_INFORMACAO: "Segurança da Informação",
  CIBERSEGURANCA: "Cibersegurança",
  PROTECAO_DE_DADOS: "Proteção de Dados",
  PRIVACIDADE_DE_DADOS: "Privacidade de Dados",
  GESTAO_DE_ACESSOS: "Gestão de Acessos",
  CONTROLE_DE_ACESSO: "Controle de Acesso",
  AUTENTICACAO_EM_DOIS_FATORES: "Autenticação em Dois Fatores",
  POLITICAS_DE_SEGURANCA: "Políticas de Segurança",
  BACKUP_E_CONTINUIDADE: "Backup e Continuidade",
  CONTINUIDADE_DE_NEGOCIOS: "Continuidade de Negócios",
  RECUPERACAO_DE_DESASTRES: "Recuperação de Desastres",
  GESTAO_DE_RISCOS_DIGITAIS: "Gestão de Riscos Digitais",
  MONITORAMENTO_DE_REDES: "Monitoramento de Redes",
  FIREWALL: "Firewall",
  ANTIVIRUS_E_ANTIMALWARE: "Antivírus e Antimalware",
  PHISHING_E_ENGENHARIA_SOCIAL: "Phishing e Engenharia Social",
  CONSCIENTIZACAO_EM_SEGURANCA: "Conscientização em Segurança",
  SEGURANCA_EM_EMAILS: "Segurança em E-mails",
  SEGURANCA_EM_ENDPOINTS: "Segurança em Endpoints",
  SEGURANCA_EM_REDES: "Segurança em Redes",
  SEGURANCA_EM_NUVEM: "Segurança em Nuvem",
  LGPD_E_SEGURANCA_DIGITAL: "LGPD e Segurança Digital",
  RESPOSTA_A_INCIDENTES: "Resposta a Incidentes",
  GESTAO_DE_INCIDENTES: "Gestão de Incidentes",
  AUDITORIA_DE_SEGURANCA: "Auditoria de Segurança",
  COMPLIANCE_DIGITAL: "Compliance Digital",
  BOAS_PRATICAS_DE_TI: "Boas Práticas de TI",

  NOVIDADES_GERAIS: "Novidades Gerais",
  ATUALIZACOES: "Atualizações",
  LANCAMENTOS: "Lançamentos",
  NOVOS_SERVICOS: "Novos Serviços",
  NOVAS_UNIDADES: "Novas Unidades",
  AVISOS_IMPORTANTES: "Avisos Importantes",
  DESTAQUES_DO_MES: "Destaques do Mês",
  CONTEUDO_RECENTE: "Conteúdo Recente",
  ACONTECEU_NA_EMPRESA: "Aconteceu na Empresa",

  FRANQUEADOS: "Franqueados",
  EXPANSAO: "Expansão",
  UNIDADES: "Unidades",
  CASES_DE_SUCESSO: "Cases de Sucesso",
  SUPORTE_AO_FRANQUEADO: "Suporte ao Franqueado",
  TREINAMENTO_DE_FRANQUEADOS: "Treinamento de Franqueados",
  GESTAO_DE_UNIDADES: "Gestão de Unidades",
  OPORTUNIDADES_DE_FRANQUIA: "Oportunidades de Franquia",
  PERFIL_DO_FRANQUEADO: "Perfil do Franqueado",
  RESULTADOS_DAS_UNIDADES: "Resultados das Unidades",
};

export const POST_SUBCATEGORY_OPTIONS_BY_CATEGORY: Record<PostCategory, PostSubcategory[]> = {
  MEDICINA_DO_TRABALHO: [
    "GERAL",
    "PCMSO",
    "EXAMES_OCUPACIONAIS",
    "EXAME_ADMISSIONAL",
    "EXAME_PERIODICO",
    "EXAME_DE_RETORNO_AO_TRABALHO",
    "EXAME_DE_MUDANCA_DE_FUNCAO",
    "EXAME_DEMISSIONAL",
    "ASO",
    "ATESTADOS_E_LAUDOS",
    "ATESTADO_DE_SAUDE_OCUPACIONAL",
    "LAUDOS_OCUPACIONAIS",
    "LAUDOS_ERGONOMICOS",
    "SAUDE_OCUPACIONAL",
    "SAUDE_MENTAL",
    "SAUDE_PREVENTIVA",
    "PROMOCAO_DA_SAUDE",
    "QUALIDADE_DE_VIDA",
    "QUALIDADE_DE_VIDA_NO_TRABALHO",
    "GINASTICA_LABORAL",
    "VACINACAO",
    "PRIMEIROS_SOCORROS",
    "FONOAUDIOLOGIA_OCUPACIONAL",
    "ERGONOMIA",
    "DOENCAS_OCUPACIONAIS",
    "DOENCAS_RESPIRATORIAS",
    "AUDICAO_E_CONSERVACAO_AUDITIVA",
    "SAUDE_VISUAL",
    "ALIMENTACAO_SAUDAVEL",
    "HABITOS_SAUDAVEIS",
    "HIDRATACAO",
    "SONO_E_DESCANSO",
    "BEM_ESTAR_NO_TRABALHO",
    "SAUDE_DA_MULHER",
    "SAUDE_DO_HOMEM",
    "SAUDE_DA_FAMILIA",
    "AUTOCUIDADO",
    "HIGIENE_PESSOAL",
    "HIGIENE_NO_TRABALHO",
    "CAMPANHAS_DE_SAUDE",
    "BOAS_PRATICAS_DE_SAUDE",
  ],

  SEGURANCA_DO_TRABALHO: [
    "GERAL",
    "PGR",
    "GRO",
    "LTCAT",
    "PPP",
    "ESOCIAL",
    "SST",
    "NORMAS_REGULAMENTADORAS",
    "NR_01",
    "NR_05",
    "NR_06",
    "NR_07",
    "NR_09",
    "NR_10",
    "NR_11",
    "NR_12",
    "NR_13",
    "NR_17",
    "NR_18",
    "NR_20",
    "NR_23",
    "NR_24",
    "NR_26",
    "NR_33",
    "NR_35",
    "TREINAMENTOS",
    "DSS",
    "SIPAT",
    "EPI",
    "EPC",
    "EPI_E_EPC",
    "ANALISE_DE_RISCO",
    "INVESTIGACAO_DE_ACIDENTES",
    "PREVENCAO_DE_ACIDENTES",
    "MAPA_DE_RISCO",
    "HIGIENE_OCUPACIONAL",
    "AGENTES_FISICOS",
    "AGENTES_QUIMICOS",
    "AGENTES_BIOLOGICOS",
    "SEGURANCA_EM_ALTURA",
    "ESPACO_CONFINADO",
    "SEGURANCA_ELETRICA",
    "SEGURANCA_EM_MAQUINAS_E_EQUIPAMENTOS",
    "COMBATE_A_INCENDIO",
    "BRIGADA_DE_INCENDIO",
    "SINALIZACAO_DE_SEGURANCA",
    "INSPECAO_DE_SEGURANCA",
    "DOCUMENTACAO_DE_SST",
    "BOAS_PRATICAS_DE_SEGURANCA",
  ],

  GESTAO_EMPRESARIAL: [
    "GERAL",
    "ADMINISTRACAO",
    "GESTAO_EMPRESARIAL",
    "GESTAO_ESTRATEGICA",
    "PLANEJAMENTO_ESTRATEGICO",
    "ORGANIZACAO_EMPRESARIAL",
    "PROCESSOS_E_PRODUTIVIDADE",
    "MAPEAMENTO_DE_PROCESSOS",
    "PADRONIZACAO_DE_PROCESSOS",
    "INDICADORES_DE_DESEMPENHO",
    "KPI",
    "BSC",
    "QUALIDADE_E_CERTIFICACOES",
    "ISO",
    "MELHORIA_CONTINUA",
    "GESTAO_DE_RISCOS",
    "GESTAO_DE_CRISES",
    "TOMADA_DE_DECISAO",
    "LIDERANCA",
    "CULTURA_EMPRESARIAL",
    "GOVERNANCA",
    "SUSTENTABILIDADE_EMPRESARIAL",
    "RESPONSABILIDADE_SOCIAL",
    "EMPREENDEDORISMO",
    "INOVACAO_E_TECNOLOGIA",
    "PLANEJAMENTO_ORGANIZACIONAL",
    "RECURSOS_HUMANOS",
    "DEPARTAMENTO_PESSOAL",
    "GESTAO_DE_PESSOAS",
    "LIDERANCA_E_GESTAO_DE_EQUIPES",
    "RECRUTAMENTO_E_SELECAO",
    "ADMISSAO_E_DEMISSAO",
    "TREINAMENTO_E_DESENVOLVIMENTO",
    "CLIMA_ORGANIZACIONAL",
    "ENGAJAMENTO",
    "RETENCAO_DE_TALENTOS",
    "AVALIACAO_DE_DESEMPENHO",
    "CARGOS_E_SALARIOS",
    "BENEFICIOS",
    "COMUNICACAO_INTERNA",
    "ENDOMARKETING",
    "DIVERSIDADE_E_INCLUSAO",
    "ETICA_PROFISSIONAL",
    "COMPORTAMENTO_ORGANIZACIONAL",
    "PRODUTIVIDADE_DA_EQUIPE",
    "BOAS_PRATICAS_DE_GESTAO",
  ],

  FINANCEIRO_E_CONTABIL: [
    "GERAL",
    "FINANCEIRO",
    "FINANCAS",
    "GESTAO_FINANCEIRA",
    "PLANEJAMENTO_FINANCEIRO",
    "FLUXO_DE_CAIXA",
    "CONTAS_A_PAGAR",
    "CONTAS_A_RECEBER",
    "CONCILIACAO_BANCARIA",
    "CAPITAL_DE_GIRO",
    "GESTAO_DE_CUSTOS",
    "GESTAO_DE_DESPESAS",
    "REDUCAO_DE_CUSTOS",
    "PRECIFICACAO",
    "INDICADORES_FINANCEIROS",
    "ORCAMENTO_EMPRESARIAL",
    "ANALISE_FINANCEIRA",
    "RENTABILIDADE",
    "LUCRATIVIDADE",
    "INADIMPLENCIA",
    "COBRANCA",
    "CREDITO",
    "INVESTIMENTOS",
    "RESERVA_FINANCEIRA",
    "EDUCACAO_FINANCEIRA",
    "CONTABILIDADE",
    "CONTABILIDADE_EMPRESARIAL",
    "CONTABILIDADE_GERENCIAL",
    "CONTABILIDADE_FISCAL",
    "ESCRITURACAO_CONTABIL",
    "BALANCO_PATRIMONIAL",
    "DRE",
    "FLUXO_DE_CAIXA_CONTABIL",
    "FECHAMENTO_CONTABIL",
    "PLANEJAMENTO_CONTABIL",
    "AUDITORIA_CONTABIL",
    "CONTROLADORIA",
    "CUSTOS_E_DESPESAS",
    "CENTRO_DE_CUSTO",
    "PATRIMONIO_EMPRESARIAL",
    "DEPRECIACAO",
    "PROVISOES",
    "OBRIGACOES_ACESSORIAS",
    "SPED",
    "ECD",
    "ECF",
    "NOTA_FISCAL",
    "FATURAMENTO",
    "FOLHA_DE_PAGAMENTO",
    "ENCARGOS_SOCIAIS",
    "IMPOSTOS_E_TRIBUTACAO",
    "PLANEJAMENTO_TRIBUTARIO",
    "OBRIGACOES_FISCAIS",
    "TRIBUTOS_FEDERAIS",
    "TRIBUTOS_ESTADUAIS",
    "TRIBUTOS_MUNICIPAIS",
    "REGIME_TRIBUTARIO",
    "SIMPLES_NACIONAL",
    "LUCRO_PRESUMIDO",
    "LUCRO_REAL",
    "RETENCOES",
    "EMISSAO_DE_NOTAS",
    "REGULARIDADE_FISCAL",
    "PARCELAMENTOS",
    "BENEFICIOS_FISCAIS",
    "BOAS_PRATICAS_FINANCEIRAS",
  ],

  JURIDICO_E_LEGISLACAO: [
    "GERAL",
    "JURIDICO",
    "LEGISLACAO",
    "DIREITO_DO_TRABALHO",
    "DIREITO_EMPRESARIAL",
    "DIREITO_PREVIDENCIARIO",
    "DIREITO_CIVIL",
    "DIREITO_TRIBUTARIO",
    "DIREITO_ADMINISTRATIVO",
    "COMPLIANCE",
    "CONTRATOS",
    "RESPONSABILIDADE_CIVIL",
    "PASSIVO_TRABALHISTA",
    "AUDITORIA_JURIDICA",
    "ADEQUACAO_LEGAL",
    "NORMAS_E_REGULAMENTACOES",
    "PORTARIAS",
    "DECRETOS",
    "OBRIGACOES_LEGAIS",
    "FISCALIZACAO",
    "DEFESA_ADMINISTRATIVA",
    "JURISPRUDENCIA",
    "REFORMA_TRABALHISTA",
    "LGPD",
    "DOCUMENTACAO_LEGAL",
    "BOAS_PRATICAS_JURIDICAS",
  ],

  INSTITUCIONAL_E_COMERCIAL: [
    "GERAL",
    "INSTITUCIONAL",
    "SOBRE_A_EMPRESA",
    "HISTORIA_DA_EMPRESA",
    "MISSAO_VISAO_E_VALORES",
    "EVENTOS",
    "FEIRAS_E_CONGRESSOS",
    "COMEMORACOES",
    "ANIVERSARIO_DA_EMPRESA",
    "DATAS_COMEMORATIVAS",
    "FERIADOS",
    "FERIADOS_NACIONAIS",
    "FERIADOS_ESTADUAIS",
    "FERIADOS_MUNICIPAIS",
    "CAMPANHAS",
    "CAMPANHAS_DE_CONSCIENTIZACAO",
    "PREMIOS_E_RECONHECIMENTOS",
    "CERTIFICACOES_E_CONQUISTAS",
    "PARCERIAS",
    "MIDIA_E_IMPRENSA",
    "COMUNICADOS_OFICIAIS",
    "NOVIDADES_INSTITUCIONAIS",
    "COMERCIAL",
    "VENDAS",
    "ATENDIMENTO_AO_CLIENTE",
    "RELACIONAMENTO_COM_CLIENTES",
    "EXPERIENCIA_DO_CLIENTE",
    "POS_VENDA",
    "MARKETING",
    "MARKETING_DIGITAL",
    "POSICIONAMENTO_DE_MARCA",
    "CAMPANHAS_COMERCIAIS",
    "BOAS_PRATICAS_COMERCIAIS",
  ],

  TECNOLOGIA_DA_INFORMACAO: [
    "GERAL",
    "SEGURANCA_DA_INFORMACAO",
    "CIBERSEGURANCA",
    "PROTECAO_DE_DADOS",
    "PRIVACIDADE_DE_DADOS",
    "GESTAO_DE_ACESSOS",
    "CONTROLE_DE_ACESSO",
    "AUTENTICACAO_EM_DOIS_FATORES",
    "POLITICAS_DE_SEGURANCA",
    "BACKUP_E_CONTINUIDADE",
    "CONTINUIDADE_DE_NEGOCIOS",
    "RECUPERACAO_DE_DESASTRES",
    "GESTAO_DE_RISCOS_DIGITAIS",
    "MONITORAMENTO_DE_REDES",
    "FIREWALL",
    "ANTIVIRUS_E_ANTIMALWARE",
    "PHISHING_E_ENGENHARIA_SOCIAL",
    "CONSCIENTIZACAO_EM_SEGURANCA",
    "SEGURANCA_EM_EMAILS",
    "SEGURANCA_EM_ENDPOINTS",
    "SEGURANCA_EM_REDES",
    "SEGURANCA_EM_NUVEM",
    "LGPD_E_SEGURANCA_DIGITAL",
    "RESPOSTA_A_INCIDENTES",
    "GESTAO_DE_INCIDENTES",
    "AUDITORIA_DE_SEGURANCA",
    "COMPLIANCE_DIGITAL",
    "BOAS_PRATICAS_DE_TI",
  ],

  NOVIDADES: [
    "GERAL",
    "NOVIDADES_GERAIS",
    "ATUALIZACOES",
    "LANCAMENTOS",
    "NOVOS_SERVICOS",
    "NOVAS_UNIDADES",
    "AVISOS_IMPORTANTES",
    "DESTAQUES_DO_MES",
    "CONTEUDO_RECENTE",
    "ACONTECEU_NA_EMPRESA",
  ],

  FRANQUIAS: [
    "GERAL",
    "FRANQUEADOS",
    "EXPANSAO",
    "UNIDADES",
    "CASES_DE_SUCESSO",
    "SUPORTE_AO_FRANQUEADO",
    "TREINAMENTO_DE_FRANQUEADOS",
    "GESTAO_DE_UNIDADES",
    "OPORTUNIDADES_DE_FRANQUIA",
    "PERFIL_DO_FRANQUEADO",
    "RESULTADOS_DAS_UNIDADES",
  ],
};

export function getPostCategoryLabel(category: PostCategory) {
  return POST_CATEGORY_LABELS[category] || "Categoria";
}

export function getPostSubcategoryLabel(subcategory: PostSubcategory) {
  return POST_SUBCATEGORY_LABELS[subcategory] || "Subcategoria";
}

export function getSubcategoryOptions(category: PostCategory) {
  return POST_SUBCATEGORY_OPTIONS_BY_CATEGORY[category].map((value) => ({
    value,
    label: getPostSubcategoryLabel(value),
  }));
}

export function isValidSubcategoryForCategory(
  category: PostCategory,
  subcategory: PostSubcategory
) {
  return POST_SUBCATEGORY_OPTIONS_BY_CATEGORY[category].includes(subcategory);
}

export function getCategoryOptions() {
  return Object.entries(POST_CATEGORY_LABELS).map(([value, label]) => ({
    value: value as PostCategory,
    label,
  }));
}